#!/usr/bin/env ruby
require 'flowcation'

config_file_name = "flowcation"

if arg = ARGV[0]  
  config_file_name = arg
end

config_file_name += ".yml"

look_up_config_paths = %w(
.
flowcation
config
config/flowcation
).map {|p| File.join(Dir.pwd, p) }



config_path = ""
look_up_config_paths.each do |path|
  next unless File.directory?(path)
  entries = Dir.entries(path)
  file = File.join(path, config_file_name)
  config_path = file if entries.include?(config_file_name)
end

unless File.exists?(config_path)
  puts "Config File Not Found"
  puts "Lookup:"
  puts look_up_config_paths
  return 1
end

config = begin
  YAML.load File.new(config_path).read
rescue Exception => e
  puts "Invalid Configuration File: #{e}"
  return 1
end

if config
  helper_file = config['flowcation']&['helper'] #config_path.sub('.yml', '.rb')
  if File.exist?(helper_file)
    existing_classes = ObjectSpace.each_object(Class).to_a
    require helper_file
    helper_class = (ObjectSpace.each_object(Class).to_a - existing_classes)[0]
    Flowcation::Settings.set('helper', helper_class.new)
  end
  processor_file = config['flowcation']&['processor'] #config_path.sub('.yml', '.rb')
  if File.exist?(processor_file)
    existing_classes = ObjectSpace.each_object(Class).to_a
    require processor_file
    processor_class = (ObjectSpace.each_object(Class).to_a - existing_classes)[0]
    Flowcation::Settings.set('processor', processor_class.new)
  end
  Flowcation::generate config
  Flowcation::Runtime.instance.write_files
end
