#!/usr/bin/env ruby
require 'flowcation'
require 'optparse' 

options = {}
option_parser = OptionParser.new do |opts|
  opts.on("-c config","--config config", "Relative Path to Yaml Configuration File") do |config|
    options[:config] = File.join(Dir.pwd, config)
  end
  opts.on("-f","--force-overwrite", "Overwrite any file flowcation attempts to generate.") do 
    options[:force_overwrite] = true
  end
end
option_parser.parse!

cmd = :generate

case ARGV[0]  
when "generate"  
  cmd = :generate
when "bootstrap"  
  cmd = :bootstrap
else  
  cmd = :generate
end  

puts "#{cmd} #{options[:config]}"

if cmd == :generate
  config = begin
    YAML.load File.new(options[:config]).read
  rescue Exception => e
    puts "Invalid Configuration."
    return 1
  end
  if config
    if overwrite = options[:force_overwrite]
      Flowcation::Settings.set('force-overwrite', true)
    end
    
    Flowcation::generate config
    Flowcation::Runtime.instance.write_files
  end
end

