#!/usr/bin/env ruby
require 'flowcation'

config_file_name = "flowcation"

if arg = ARGV[0]  
  config_file_name = arg
end

config_file_name += ".yml"

look_up_config_paths = %w(
.
flowcation
config
config/flowcation
).map {|p| File.join(Dir.pwd, p) }



config_path = ""
look_up_config_paths.each do |path|
  next unless File.directory?(path)
  entries = Dir.entries(path)
  file = File.join(path, config_file_name)
  config_path = file if entries.include?(config_file_name)
end

unless File.exists?(config_path)
  puts "Config File Not Found"
  puts "Lookup:"
  puts look_up_config_paths
  return 1
end

config = begin
  YAML.load File.new(config_path).read
rescue Exception => e
  puts "Invalid Configuration File: #{e}"
  return 1
end

if config
  Flowcation::generate config
  Flowcation::Runtime.instance.write_files
end
